In [3]:
import numpy as np

In [4]:
a = [[1,2,3],[4,5,6]]
np.sum(a, axis=1)

array([ 6, 15])

In [5]:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [6]:
Y = np.array([[1,0],[0,1],[1,0]])

In [11]:
Y==1

array([[ True, False],
       [False,  True],
       [ True, False]])

In [10]:
T_ind = np.where(Y == 1)
T_ind

(array([0, 1, 2], dtype=int64), array([0, 1, 0], dtype=int64))

In [8]:
T_ind

(array([0, 1, 2], dtype=int64), array([0, 1, 0], dtype=int64))